- name: Disable Kerberos pre-authentication for Administrators group members
  hosts: all
  tasks:
    - name: Execute disable_kerberos_preauth.ps1
      ansible.windows.win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File C:\vagrant\scripts\red\vuln_kerberos_properties_preauth_priv.ps1
