- name: Configure role(s) on a Windows server instance
  hosts: all
  tasks:
    - name: Run powershell commands to prepare the DC
      ansible.windows.win_powershell:
        script: |
          Add-WindowsFeature AD-Domain-Services
          Set-TimeZone -Name "Romance Standard Time"
      register: dc_prep

    - name: Change the hostname
      ansible.windows.win_hostname:
        name: dc
      register: hostname
      when: not hostname_changed

    - name: Reboot if hostname change required
      ansible.windows.win_reboot:
      when: hostname.reboot_required
      register: hostname_rebooted

    - name: Set up static IP address
      ansible.windows.win_shell: |
        $interface = Get-NetAdapter | Where-Object {$_.Status -eq 'Up'}
        $existingIP = Get-NetIPAddress -InterfaceAlias $interface.InterfaceAlias | Where-Object {$_.IPAddress -eq '10.0.2.100'}
        if (-not $existingIP) {
          New-NetIPAddress -InterfaceAlias $interface.InterfaceAlias -IPAddress 10.0.2.100 -PrefixLength 24 -DefaultGateway 10.0.2.2
          Set-DnsClientServerAddress -InterfaceAlias $interface.InterfaceAlias -ServerAddresses 10.0.2.100
        }
      async: 100
      poll: 0

    - name: Wait for the network to come back up
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 5985
        delay: 10
        state: started
      register: wait_result
      delegate_to: localhost

    - name: Install ADDS role and configure it with minimal options
      ansible.windows.win_domain:
        dns_domain_name: bzh.local
        safe_mode_password: password123!
      register: domain_install
      when: not domain_installed

    - name: Reboot after promotion
      ansible.windows.win_reboot:
      when: domain_install.reboot_required
      register: domain_rebooted

    - name: Download BadBlood
      ansible.windows.win_get_url:
        url: "https://github.com/davidprowe/BadBlood/archive/master.zip"
        dest: "C:\\BadBlood.zip"
      when: not badblood_downloaded

    - name: Unzip BadBlood
      community.windows.win_unzip:
        src: "C:\\BadBlood.zip"
        dest: "C:\\BadBlood"
        creates: "C:\\BadBlood\\BadBlood-master"
      when: not badblood_unzipped

    - name: Execute BadBlood
      ansible.windows.win_powershell:
        script: |
          Set-Location "C:\\BadBlood\\BadBlood-master"
          .\\Invoke-BadBlood.ps1
      when: not badblood_executed

    - name: Set flags for completed tasks
      ansible.builtin.set_fact:
        hostname_changed: true
        domain_installed: true
        badblood_downloaded: true
        badblood_unzipped: true
        badblood_executed: true
      when: (hostname_rebooted.changed or domain_rebooted.changed)
